filebeat.inputs:
  - type: log

    # Change to true to enable this input configuration.
    enabled: true

    # Paths that should be crawled and fetched. Glob based paths.
    paths:
      - /var/webapp/logs/*.log
    # 这三行可以将 json 内容解析成键值对的形式，否则会将全部 json 内容放到一个 message 字段里
    # 默认json日志在filebeat发送内容的json字段内，如需放在根root下，需打开此开关
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true

    multiline.pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}"
    # 是否取反，即当不以日期格式开头时
    multiline.negate: true
    # 匹配规则，before 还是 after。三个配置加起来的意思是：  读取的行不以日期开头时，合并到以日期开头为一行。例如堆栈异常多行信息应当合并为一行消息
    multiline.match: after

#==================== Elasticsearch template setting ==========================
setup.template.name: "log-"
setup.template.pattern: "log-*"
setup.template.overwrite: false
setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 1

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # 输出到ES
  hosts: [":9200"]
  # 输出的索引名称，需要指定setup.template.name和setup.template.pattern
  index: "log-JG-%{+yyyy.MM.dd}"
  # Protocol - either `http` (default) or `https`.
  # protocol: "https"
  # Authentication credentials - either API key or username/password.
  # api_key: "id:api_key"
  # username: "elastic"
  # password: "changeme"
