version: "3"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - C:\worktool\dockerData\nacos\standalone-logs\:/home/nacos/logs
      - C:\worktool\dockerData\nacos\config\custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "7748:8848"
