version: '3.2'

services:
  elasticsearch:
    # image: elasticsearch:7.9.3
    build: 
      context: elasticsearch/
    container_name: elasticsearch
    volumes:
      - type: bind
        source: .\elasticsearch\config\elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - C:\worktool\dockerData\es2\data:/usr/share/elasticsearch/data
      - C:\worktool\dockerData\es2\logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: wiki
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elknet

  logstash:
#    image: logstash:7.9.3
    build:
      context: logstash/
    container_name: logstash
    volumes:
      - type: bind
        source: .\logstash\config\logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: .\logstash\pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
#      - .\logstash\connect\mysql-connector-java-8.0.17.jar:/usr/share/logstash/mysql-connector-java-8.0.17.jar
#      - .\logstash\config\jdbc-page.sql:/usr/share/logstash/config/jdbc-page.sql
      # 中文分词模板
      - .\logstash\config\ik_zh_template.json:/usr/share/logstash/config/ik_zh_template.json
      # - .\logstash\config\last_id.txt:/usr/share/logstash/config/last_id.txt
      # - type: bind
      #   source: .\logstash\config\last_id.txt
      #   target: /usr/share/logstash/config/last_id.txt
      #   read_only: false
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elknet
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.9.3
    container_name: kibana
    volumes:
      - type: bind
        source: .\kibana\config\kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - elknet
    depends_on:
      - elasticsearch

networks:
  elknet:
    driver: bridge

