version: "3"
# 哨兵模式-哨兵配置文件
services:
  redis-sentinel1:
    image: redis
    container_name: redis-sentinel1
    ports:
      - "16394:16394"
    volumes:
      - C:\worktool\dockerData\redis-sentinel\config\sentinel1.conf:/usr/local/etc/redis/redis.conf
      - C:\worktool\dockerData\redis-sentinel\data\sentinel1:/data
    command: redis-sentinel /usr/local/etc/redis/redis.conf
  
  redis-sentinel2:
    image: redis
    container_name: redis-sentinel2
    ports:
      - "16395:16395"
    volumes:
      - C:\worktool\dockerData\redis-sentinel\config\sentinel2.conf:/usr/local/etc/redis/redis.conf
      - C:\worktool\dockerData\redis-sentinel\data\sentinel2:/data
    # command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master 6391
    command: redis-sentinel /usr/local/etc/redis/redis.conf

  
  redis-sentinel3:
    image: redis
    container_name: redis-sentinel3
    ports:
      - "16396:16396"
    volumes:
      - C:\worktool\dockerData\redis-sentinel\config\sentinel3.conf:/usr/local/etc/redis/redis.conf
      - C:\worktool\dockerData\redis-sentinel\data\sentinel3:/data
    # command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master1 6391
    command: redis-sentinel /usr/local/etc/redis/redis.conf

networks:
  default:
    external:
      name: redis_default