version: "3"
# 主从复制模式
services:
  redis-master1:
    image: redis
    container_name: redis-master-1
    ports:
      - "6381:6381"
    volumes:
      - C:\worktool\dockerData\redis-master\conf\master-1.conf:/usr/local/etc/redis/redis.conf
      - C:\worktool\dockerData\redis-master\data\6381:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  
  redis-slave-1:
    image: redis
    container_name: redis-slave-1
    ports:
      - "6388:6388"
    volumes:
      - C:\worktool\dockerData\redis-master\conf\slave-1.conf:/usr/local/etc/redis/redis.conf
      - C:\worktool\dockerData\redis-master\data\6382:/data
    # 添加--salveof，从节点开启主从复制
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master-1 6381
  
  redis-slave-2:
    image: redis
    container_name: redis-slave-2
    ports:
      - "6389:6389"
    volumes:
      - C:\worktool\dockerData\redis-master\conf\slave-2.conf:/usr/local/etc/redis/redis.conf
      - C:\worktool\dockerData\redis-master\data\6383:/data
    # 添加--salveof，从节点开启主从复制
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master-1 6381
