version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - C:\worktool\dockerData\redis\redis.conf:/usr/local/etc/redis/redis.conf
      - C:\worktool\dockerData\redis\data:/data  
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment: 
      # 设置时区
      - TZ=Asia/Shanghai
    restart: unless-stopped